### <p style="text-align: center;"> **Name:** Shahzaib Khan &ensp;&ensp;&ensp;&ensp;&ensp;&ensp; **Roll No:** 19K-0273 &ensp;&ensp;&ensp;&ensp;&ensp;&ensp; **Section:** BCS-8B</p>

In [389]:
# Import libraries
import numpy as np
import pandas as pd
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

### **Question: 1**

In [390]:
# Part (a)
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
training = pd.read_csv("data/iris.csv", names=names, header=0)
training.head()

   sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [391]:
# Part (b)
print('Size:', training.shape)

Size: (150, 5)

In [392]:
# Part (c)
print('class distribution\n', training.groupby('class').size())

class distribution
 class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

In [393]:
# Part (d)
array = training.values
X = array[:,0:4]
Y = array[:,4]
t_size = 0.20
seed = 7

X_train_I, X_test_I, Y_train_I, Y_test_I = train_test_split(X, Y, test_size=t_size, random_state=seed)

In [394]:
# Part (e)
knn = KNeighborsClassifier()
knn.fit(X_train_I, Y_train_I)
predictions = knn.predict(X_test_I)
print('score: ', accuracy_score(Y_test_I, predictions))
print('\nconfusion_matrix:\n', confusion_matrix(Y_test_I, predictions))
print('\nclassification_report:\n', classification_report(Y_test_I, predictions))

score:  0.9

confusion_matrix:
 [[ 7  0  0]
 [ 0 11  1]
 [ 0  2  9]]

classification_report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.85      0.92      0.88        12
 Iris-virginica       0.90      0.82      0.86        11

       accuracy                           0.90        30
      macro avg       0.92      0.91      0.91        30
   weighted avg       0.90      0.90      0.90        30

In [395]:
# Part (f)
for i in range(1, 11):
    f = KNeighborsClassifier(n_neighbors=i)
    f.fit(X_train_I, Y_train_I)
    f_pred = f.predict(X_test_I)
    print(f"For {i} neighbors: {accuracy_score(Y_test_I, f_pred):.3f}")

For 1 neighbors: 0.900
For 2 neighbors: 0.933
For 3 neighbors: 0.900
For 4 neighbors: 0.933
For 5 neighbors: 0.900
For 6 neighbors: 0.867
For 7 neighbors: 0.867
For 8 neighbors: 0.900
For 9 neighbors: 0.900
For 10 neighbors: 0.900

In [396]:
# Part (g)
for i in range(1, 11):
    X_train_I, X_test_I, Y_train_I, Y_test_I = train_test_split(X, Y, test_size=t_size, random_state=i)

    g = KNeighborsClassifier()
    g.fit(X_train_I, Y_train_I)
    f_pred = g.predict(X_test_I)
    print(f"For seed {i}: {accuracy_score(Y_test_I, f_pred):.3f}")

For seed 1: 1.000
For seed 2: 1.000
For seed 3: 0.967
For seed 4: 0.967
For seed 5: 0.933
For seed 6: 0.967
For seed 7: 0.900
For seed 8: 0.900
For seed 9: 1.000
For seed 10: 0.967

### **Question: 2**

In [397]:
# Part (a)
names = ['date', 'Temperature', 'Humidity', 'Light', 'CO2', 'HumidityRatio', 'Occupancy']
training = pd.read_csv("data/datatraining.csv", names=names, header=0)
training.head()

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
0,4/2/2015 17:51,23.18,27.2720,426.0,721.25,0.004793,1
1,4/2/2015 17:51,23.15,27.2675,429.5,714.00,0.004783,1
2,4/2/2015 17:53,23.15,27.2450,426.0,713.50,0.004779,1
3,4/2/2015 17:54,23.15,27.2000,426.0,708.25,0.004772,1
4,4/2/2015 17:55,23.10,27.2000,426.0,704.50,0.004757,1

In [398]:
testing = pd.read_csv("data/datatest.csv", names=names, header=0)
testing.head()

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
0,11/2/2015 14:48,21.7600,31.133333,437.333333,1029.666667,0.005021,1
1,11/2/2015 14:49,21.7900,31.000000,437.333333,1000.000000,0.005009,1
2,11/2/2015 14:50,21.7675,31.122500,434.000000,1003.750000,0.005022,1
3,11/2/2015 14:51,21.7675,31.122500,439.000000,1009.500000,0.005022,1
4,11/2/2015 14:51,21.7900,31.133333,437.333333,1005.666667,0.005030,1

In [399]:
# Part (b)
print('Size:', training.shape)

Size: (8143, 7)

In [400]:
# Part (c)
print('class distribution\n', training.groupby('Occupancy').size())

class distribution
 Occupancy
0    6414
1    1729
dtype: int64

In [401]:
# Part (d)
array = training.values
X_train_II = array[:,1:6]
Y_train_II = array[:,6].astype('int') # here explicit conversion is required 

array = testing.values
X_test_II = array[:,1:6]
Y_test_II = array[:,6].astype('int')

print(X_train_II)

[[23.18 27.272 426.0 721.25 0.004792988]
 [23.15 27.2675 429.5 714.0 0.004783441]
 [23.15 27.245 426.0 713.5 0.004779464]
 ...
 [21.1 36.095 433.0 798.5 0.005595639]
 [21.1 36.26 433.0 820.3333333 0.005621449]
 [21.1 36.2 447.0 821.0 0.005612064]]

In [402]:
# Part (e)
knn = KNeighborsClassifier()
knn.fit(X_train_II, Y_train_II)
predictions = knn.predict(X_test_II)
print(f'score: {accuracy_score(Y_test_II, predictions):.3f}')
print('\nconfusion_matrix:\n', confusion_matrix(Y_test_II, predictions))
print('\nclassification_report:\n', classification_report(Y_test_II, predictions))

score: 0.962

confusion_matrix:
 [[7385  318]
 [  51 1998]]

classification_report:
               precision    recall  f1-score   support

           0       0.99      0.96      0.98      7703
           1       0.86      0.98      0.92      2049

    accuracy                           0.96      9752
   macro avg       0.93      0.97      0.95      9752
weighted avg       0.97      0.96      0.96      9752

In [403]:
# Part (f)
for i in range(1, 11):
    f = KNeighborsClassifier(n_neighbors=i)
    f.fit(X_train_II, Y_train_II)
    f_pred = f.predict(X_test_II)
    print(f"For {i} neighbors: {accuracy_score(Y_test_II, f_pred):.3f}")

For 1 neighbors: 0.950
For 2 neighbors: 0.953
For 3 neighbors: 0.958
For 4 neighbors: 0.954
For 5 neighbors: 0.962
For 6 neighbors: 0.963
For 7 neighbors: 0.965
For 8 neighbors: 0.966
For 9 neighbors: 0.966
For 10 neighbors: 0.966

### **Question: 3**

In [ ]:
# Calculate (Vectorized) Chi-squared distance
def get_chi_squared_distance(X_test, X_train):
    X_test = np.asarray(X_test, dtype=float)
    X_train = np.asarray(X_train, dtype=float)
    # Broadcasting: (n_test, n_train, n_features)
    diff = X_test[:, np.newaxis, :] - X_train[np.newaxis, :, :]
    sum_ab = X_test[:, np.newaxis, :] + X_train[np.newaxis, :, :] + 1e-10
    return np.sum((diff ** 2) / sum_ab, axis=2)

# Optimized Custom kNN classifier
def custom_kNN(X_train, Y_train, X_test, k):
    distances = get_chi_squared_distance(X_test, X_train) # Shape: (n_test, n_train)
    indices = np.argsort(distances, axis=1)[:, :k] # Shape: (n_test, k)
    k_classes = Y_train[indices] # Shape: (n_test, k)
    predictions = [Counter(row).most_common(1)[0][0] for row in k_classes] # count occurrences to get the most common class
    return np.array(predictions)

**Part I: Iris Dataset**

In [405]:
# Reuse data from Question 1
# (a) Already loaded: training
# (b) Already printed: (150, 5)
# (c) Already printed: 50, 50, 50
# (d) Already prepared & splitted data: X_train_I, Y_train_I, X_test_I, Y_test_I

# (e) Apply custom kNN with default k=5
predictions = custom_kNN(X_train_I, Y_train_I, X_test_I, k=5)
print(f'score: {accuracy_score(Y_test_I, predictions):.3f}')
print('\nconfusion_matrix:\n', confusion_matrix(Y_test_I, predictions))
print('\nclassification_report:\n', classification_report(Y_test_I, predictions))

score: 0.967

confusion_matrix:
 [[10  0  0]
 [ 0 12  1]
 [ 0  0  7]]

classification_report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.88      1.00      0.93         7

       accuracy                           0.97        30
      macro avg       0.96      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30

In [406]:
# (f) Vary k from 1 to 10
for k in range(1, 11):
    predictions = custom_kNN(X_train_I, Y_train_I, X_test_I, k)
    print(f"For {k} neighbors: {accuracy_score(Y_test_I, predictions):.3f}")

For 1 neighbors: 0.967
For 2 neighbors: 0.967
For 3 neighbors: 0.967
For 4 neighbors: 0.967
For 5 neighbors: 0.967
For 6 neighbors: 0.967
For 7 neighbors: 1.000
For 8 neighbors: 0.967
For 9 neighbors: 1.000
For 10 neighbors: 0.967

In [407]:
# (g) Vary seed from 1 to 10
for seed in range(1, 11):
    X_train_I, X_test_I, Y_train_I, Y_test_I = train_test_split(X, Y, test_size=t_size, random_state=seed)
    predictions = custom_kNN(X_train_I, Y_train_I, X_test_I, k=5)
    print(f"For seed {seed}: {accuracy_score(Y_test_I, predictions):.3f}")

For seed 1: 0.967
For seed 2: 0.967
For seed 3: 0.967
For seed 4: 0.933
For seed 5: 0.933
For seed 6: 1.000
For seed 7: 0.867
For seed 8: 0.900
For seed 9: 1.000
For seed 10: 0.967

**Part II: Occupancy Detection Dataset**

In [408]:
# Reuse data from Question 2
# (a) Already loaded: training, testing
# (b) Already printed: (8143, 7)
# (c) Already printed: 6414, 1729
# (d) Already prepared & splitted data: X_train_II, Y_train_II, X_test_II, Y_test_II

# (e) Apply custom kNN with default k=5
predictions = custom_kNN(X_train_II, Y_train_II, X_test_II, k=5)
print(f'score: {accuracy_score(Y_test_II, predictions):.3f}')
print('\nconfusion_matrix:\n', confusion_matrix(Y_test_II, predictions))
print('\nclassification_report:\n', classification_report(Y_test_II, predictions))

score: 0.957

confusion_matrix:
 [[7403  300]
 [ 116 1933]]

classification_report:
               precision    recall  f1-score   support

           0       0.98      0.96      0.97      7703
           1       0.87      0.94      0.90      2049

    accuracy                           0.96      9752
   macro avg       0.93      0.95      0.94      9752
weighted avg       0.96      0.96      0.96      9752

In [409]:
# (f) Vary k from 1 to 10
print("\nVarying k:")
for k in range(1, 11):
    predictions = custom_kNN(X_train_II, Y_train_II, X_test_II, k)
    print(f"For {k} neighbors: {accuracy_score(Y_test_II, predictions):.3f}")

Varying k:
For 1 neighbors: 0.950
For 2 neighbors: 0.950
For 3 neighbors: 0.950
For 4 neighbors: 0.954
For 5 neighbors: 0.957
For 6 neighbors: 0.959
For 7 neighbors: 0.959
For 8 neighbors: 0.960
For 9 neighbors: 0.960
For 10 neighbors: 0.961